version: '3.1'
services:
    database:
      image: postgres
      container_name: toolbox-database
      environment:
        POSTGRES_PASSWORD: docker
        POSTGRES_USER: postgres
        POSTGRES_DB: toolbox_database
      ports:
        - '5438:5432'
      volumes:
        - toolbox_database:/var/lib/postgresql/data

volumes:
  toolbox_database: